"""初始结构：评测任务、结果与明细

把当前模型定为第一版。此前用的是 Base.metadata.create_all，它只建缺失的表、
从不修改已存在的表，因此模型一改、存量库就会出现
"no such column" 这类运行时错误。

Revision ID: d3cb3bc90ca1
Revises:
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3cb3bc90ca1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_result',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=255), nullable=False),
    sa.Column('content_hash', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('gate_passed', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=8), nullable=True),
    sa.Column('severity_counts', sa.JSON(), nullable=False),
    sa.Column('evaluator_version', sa.String(length=64), nullable=True),
    sa.Column('profile', sa.String(length=64), nullable=True),
    sa.Column('policy_digest', sa.String(length=80), nullable=True),
    sa.Column('incomplete_scans', sa.JSON(), nullable=False),
    sa.Column('report_json_uri', sa.Text(), nullable=True),
    sa.Column('report_html_uri', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'content_hash', name='uq_skill_content')
    )
    with op.batch_alter_table('evaluation_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_result_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_result_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_result_status'), ['status'], unique=False)

    op.create_table('evaluation_task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=255), nullable=False),
    sa.Column('skill_version', sa.String(length=128), nullable=True),
    sa.Column('content_hash', sa.String(length=80), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('queue', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_task_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_task_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_task_state'), ['state'], unique=False)

    op.create_table('evaluation_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('validator_name', sa.String(length=128), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['evaluation_result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_detail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_detail_result_id'), ['result_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation_detail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_detail_result_id'))

    op.drop_table('evaluation_detail')
    with op.batch_alter_table('evaluation_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_task_state'))
        batch_op.drop_index(batch_op.f('ix_evaluation_task_skill_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_task_content_hash'))

    op.drop_table('evaluation_task')
    with op.batch_alter_table('evaluation_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_result_status'))
        batch_op.drop_index(batch_op.f('ix_evaluation_result_skill_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_result_content_hash'))

    op.drop_table('evaluation_result')
    # ### end Alembic commands ###
